version: "3"
services:
  goblin:
    image: goblin
    container_name: goblin
    ports:
      - "8000:8000"
    networks:
      - service
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: '300M'
      restart_policy:
        condition: any
        delay: 5s
        # max_attempts: 3
        window: 120s
    environment:
      - REDIS_URL=redis://tikredis:6379
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  redis:
    image: redis
    container_name: tikredis
    ports:
      - "6379:6379"
    networks:
      - service
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '2'
          memory: '100M'
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
    healthcheck:
      test: [ "CMD", "redis-cli", "-p", "6379", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3
networks:
  service: